import type { Metadata } from "next";
import { Geist, Geist_Mono, Adamina, Abhaya_Libre, Inter, } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import About from "./about/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const adamina = Adamina({
  weight: "400", // ✅ must include this line
  variable: "--font-adamina",
  subsets: ["latin"],
});

const abhayaLibre = Abhaya_Libre({
  weight: ["500", "800"], // ✅ must include this line
  variable: "--font-abhaya-libre",
  subsets: ["latin"],
});

const inter = Inter({
  weight: "700", // ✅ must include this line
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Radu Ghimp portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${adamina.variable} ${abhayaLibre.variable} ${inter.variable} antialiased`}
      >
        <Header />
        {children}
        <About />
      </body>
    </html>
  );
}
